packages:
  - "app"
  - "website"
  - "api"
  - "test"
  - "deploy"
allowBuilds:
  "@pulumi/kubernetes": false
  "@sentry/cli": false
  "@swc/core": false
  bcrypt: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
minimumReleaseAge: 120
minimumReleaseAgeExclude:
  - '@banksnussman/osrm@0.0.4'
  - '@banksnussman/photon@0.0.5'
  - car-info@0.2.6
