packages:
  - "app"
  - "website"
  - "api"
  - "test"
  - "deploy"
allowBuilds:
  "@pulumi/kubernetes": false
  "@sentry/cli": false
  "@swc/core": false
  bcrypt: set this to true or false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
minimumReleaseAge: 120
