/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountDeleteRouteImport } from './routes/account/delete'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminRedisRouteImport } from './routes/admin/redis'
import { Route as PasswordChangeRouteImport } from './routes/password/change'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as AccountVerifyIdRouteImport } from './routes/account/verify.$id'
import { Route as AdminBeepersIndexRouteImport } from './routes/admin/beepers/index'
import { Route as AdminBeepsIndexRouteImport } from './routes/admin/beeps/index'
import { Route as AdminBeepsBeepIdRouteImport } from './routes/admin/beeps/$beepId'
import { Route as AdminBeepsActiveRouteImport } from './routes/admin/beeps/active'
import { Route as AdminCarsIndexRouteImport } from './routes/admin/cars/index'
import { Route as AdminFeedbackIndexRouteImport } from './routes/admin/feedback/index'
import { Route as AdminLeaderboardsIndexRouteImport } from './routes/admin/leaderboards/index'
import { Route as AdminLeaderboardsBeepsRouteImport } from './routes/admin/leaderboards/beeps'
import { Route as AdminLeaderboardsRidesRouteImport } from './routes/admin/leaderboards/rides'
import { Route as AdminNotificationsIndexRouteImport } from './routes/admin/notifications/index'
import { Route as AdminRatingsIndexRouteImport } from './routes/admin/ratings/index'
import { Route as AdminRatingsRatingIdRouteImport } from './routes/admin/ratings/$ratingId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminReportsReportIdRouteImport } from './routes/admin/reports/$reportId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminUsersDomainRouteImport } from './routes/admin/users/domain'
import { Route as PasswordResetIdRouteImport } from './routes/password/reset.$id'
import { Route as AdminUsersUserIdSplatRouteImport } from './routes/admin/users/$userId/$'
import { Route as AdminUsersUserIdBeepsRouteImport } from './routes/admin/users/$userId/beeps'
import { Route as AdminUsersUserIdCarsRouteImport } from './routes/admin/users/$userId/cars'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'
import { Route as AdminUsersUserIdLocationRouteImport } from './routes/admin/users/$userId/location'
import { Route as AdminUsersUserIdPaymentsRouteImport } from './routes/admin/users/$userId/payments'
import { Route as AdminUsersUserIdQueueRouteImport } from './routes/admin/users/$userId/queue'
import { Route as AdminUsersUserIdRatingsRouteImport } from './routes/admin/users/$userId/ratings'
import { Route as AdminUsersUserIdReportsRouteImport } from './routes/admin/users/$userId/reports'
import { Route as AdminUsersUserIdRideRouteImport } from './routes/admin/users/$userId/ride'
import { Route as AdminUsersUserIdEditSplatRouteImport } from './routes/admin/users/$userId/edit/$'
import { Route as AdminUsersUserIdEditLocationRouteImport } from './routes/admin/users/$userId/edit/location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedisRoute = AdminRedisRouteImport.update({
  id: '/redis',
  path: '/redis',
  getParentRoute: () => AdminRoute,
} as any)
const PasswordChangeRoute = PasswordChangeRouteImport.update({
  id: '/password/change',
  path: '/password/change',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyIdRoute = AccountVerifyIdRouteImport.update({
  id: '/account/verify/$id',
  path: '/account/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBeepersIndexRoute = AdminBeepersIndexRouteImport.update({
  id: '/beepers/',
  path: '/beepers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeepsIndexRoute = AdminBeepsIndexRouteImport.update({
  id: '/beeps/',
  path: '/beeps/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeepsBeepIdRoute = AdminBeepsBeepIdRouteImport.update({
  id: '/beeps/$beepId',
  path: '/beeps/$beepId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeepsActiveRoute = AdminBeepsActiveRouteImport.update({
  id: '/beeps/active',
  path: '/beeps/active',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsIndexRoute = AdminCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackIndexRoute = AdminFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardsIndexRoute = AdminLeaderboardsIndexRouteImport.update({
  id: '/leaderboards/',
  path: '/leaderboards/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardsBeepsRoute = AdminLeaderboardsBeepsRouteImport.update({
  id: '/leaderboards/beeps',
  path: '/leaderboards/beeps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardsRidesRoute = AdminLeaderboardsRidesRouteImport.update({
  id: '/leaderboards/rides',
  path: '/leaderboards/rides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRatingsIndexRoute = AdminRatingsIndexRouteImport.update({
  id: '/ratings/',
  path: '/ratings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRatingsRatingIdRoute = AdminRatingsRatingIdRouteImport.update({
  id: '/ratings/$ratingId',
  path: '/ratings/$ratingId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsReportIdRoute = AdminReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersDomainRoute = AdminUsersDomainRouteImport.update({
  id: '/users/domain',
  path: '/users/domain',
  getParentRoute: () => AdminRoute,
} as any)
const PasswordResetIdRoute = PasswordResetIdRouteImport.update({
  id: '/password/reset/$id',
  path: '/password/reset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdSplatRoute = AdminUsersUserIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdBeepsRoute = AdminUsersUserIdBeepsRouteImport.update({
  id: '/beeps',
  path: '/beeps',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdCarsRoute = AdminUsersUserIdCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdLocationRoute =
  AdminUsersUserIdLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AdminUsersUserIdRoute,
  } as any)
const AdminUsersUserIdPaymentsRoute =
  AdminUsersUserIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AdminUsersUserIdRoute,
  } as any)
const AdminUsersUserIdQueueRoute = AdminUsersUserIdQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdRatingsRoute = AdminUsersUserIdRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdReportsRoute = AdminUsersUserIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdRideRoute = AdminUsersUserIdRideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const AdminUsersUserIdEditSplatRoute =
  AdminUsersUserIdEditSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AdminUsersUserIdEditRoute,
  } as any)
const AdminUsersUserIdEditLocationRoute =
  AdminUsersUserIdEditLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AdminUsersUserIdEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/redis': typeof AdminRedisRoute
  '/password/change': typeof PasswordChangeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/profile/edit': typeof ProfileEditRoute
  '/account/verify/$id': typeof AccountVerifyIdRoute
  '/admin/beeps/$beepId': typeof AdminBeepsBeepIdRoute
  '/admin/beeps/active': typeof AdminBeepsActiveRoute
  '/admin/leaderboards/beeps': typeof AdminLeaderboardsBeepsRoute
  '/admin/leaderboards/rides': typeof AdminLeaderboardsRidesRoute
  '/admin/ratings/$ratingId': typeof AdminRatingsRatingIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/domain': typeof AdminUsersDomainRoute
  '/password/reset/$id': typeof PasswordResetIdRoute
  '/admin/beepers/': typeof AdminBeepersIndexRoute
  '/admin/beeps/': typeof AdminBeepsIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/leaderboards/': typeof AdminLeaderboardsIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/ratings/': typeof AdminRatingsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/users/$userId/$': typeof AdminUsersUserIdSplatRoute
  '/admin/users/$userId/beeps': typeof AdminUsersUserIdBeepsRoute
  '/admin/users/$userId/cars': typeof AdminUsersUserIdCarsRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRouteWithChildren
  '/admin/users/$userId/location': typeof AdminUsersUserIdLocationRoute
  '/admin/users/$userId/payments': typeof AdminUsersUserIdPaymentsRoute
  '/admin/users/$userId/queue': typeof AdminUsersUserIdQueueRoute
  '/admin/users/$userId/ratings': typeof AdminUsersUserIdRatingsRoute
  '/admin/users/$userId/reports': typeof AdminUsersUserIdReportsRoute
  '/admin/users/$userId/ride': typeof AdminUsersUserIdRideRoute
  '/admin/users/$userId/edit/$': typeof AdminUsersUserIdEditSplatRoute
  '/admin/users/$userId/edit/location': typeof AdminUsersUserIdEditLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/redis': typeof AdminRedisRoute
  '/password/change': typeof PasswordChangeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/profile/edit': typeof ProfileEditRoute
  '/account/verify/$id': typeof AccountVerifyIdRoute
  '/admin/beeps/$beepId': typeof AdminBeepsBeepIdRoute
  '/admin/beeps/active': typeof AdminBeepsActiveRoute
  '/admin/leaderboards/beeps': typeof AdminLeaderboardsBeepsRoute
  '/admin/leaderboards/rides': typeof AdminLeaderboardsRidesRoute
  '/admin/ratings/$ratingId': typeof AdminRatingsRatingIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/domain': typeof AdminUsersDomainRoute
  '/password/reset/$id': typeof PasswordResetIdRoute
  '/admin/beepers': typeof AdminBeepersIndexRoute
  '/admin/beeps': typeof AdminBeepsIndexRoute
  '/admin/cars': typeof AdminCarsIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/leaderboards': typeof AdminLeaderboardsIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/ratings': typeof AdminRatingsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/users/$userId/$': typeof AdminUsersUserIdSplatRoute
  '/admin/users/$userId/beeps': typeof AdminUsersUserIdBeepsRoute
  '/admin/users/$userId/cars': typeof AdminUsersUserIdCarsRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRouteWithChildren
  '/admin/users/$userId/location': typeof AdminUsersUserIdLocationRoute
  '/admin/users/$userId/payments': typeof AdminUsersUserIdPaymentsRoute
  '/admin/users/$userId/queue': typeof AdminUsersUserIdQueueRoute
  '/admin/users/$userId/ratings': typeof AdminUsersUserIdRatingsRoute
  '/admin/users/$userId/reports': typeof AdminUsersUserIdReportsRoute
  '/admin/users/$userId/ride': typeof AdminUsersUserIdRideRoute
  '/admin/users/$userId/edit/$': typeof AdminUsersUserIdEditSplatRoute
  '/admin/users/$userId/edit/location': typeof AdminUsersUserIdEditLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/redis': typeof AdminRedisRoute
  '/password/change': typeof PasswordChangeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/profile/edit': typeof ProfileEditRoute
  '/account/verify/$id': typeof AccountVerifyIdRoute
  '/admin/beeps/$beepId': typeof AdminBeepsBeepIdRoute
  '/admin/beeps/active': typeof AdminBeepsActiveRoute
  '/admin/leaderboards/beeps': typeof AdminLeaderboardsBeepsRoute
  '/admin/leaderboards/rides': typeof AdminLeaderboardsRidesRoute
  '/admin/ratings/$ratingId': typeof AdminRatingsRatingIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/domain': typeof AdminUsersDomainRoute
  '/password/reset/$id': typeof PasswordResetIdRoute
  '/admin/beepers/': typeof AdminBeepersIndexRoute
  '/admin/beeps/': typeof AdminBeepsIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/leaderboards/': typeof AdminLeaderboardsIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/ratings/': typeof AdminRatingsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/users/$userId/$': typeof AdminUsersUserIdSplatRoute
  '/admin/users/$userId/beeps': typeof AdminUsersUserIdBeepsRoute
  '/admin/users/$userId/cars': typeof AdminUsersUserIdCarsRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRouteWithChildren
  '/admin/users/$userId/location': typeof AdminUsersUserIdLocationRoute
  '/admin/users/$userId/payments': typeof AdminUsersUserIdPaymentsRoute
  '/admin/users/$userId/queue': typeof AdminUsersUserIdQueueRoute
  '/admin/users/$userId/ratings': typeof AdminUsersUserIdRatingsRoute
  '/admin/users/$userId/reports': typeof AdminUsersUserIdReportsRoute
  '/admin/users/$userId/ride': typeof AdminUsersUserIdRideRoute
  '/admin/users/$userId/edit/$': typeof AdminUsersUserIdEditSplatRoute
  '/admin/users/$userId/edit/location': typeof AdminUsersUserIdEditLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/download'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account/delete'
    | '/admin/health'
    | '/admin/payments'
    | '/admin/redis'
    | '/password/change'
    | '/password/forgot'
    | '/profile/edit'
    | '/account/verify/$id'
    | '/admin/beeps/$beepId'
    | '/admin/beeps/active'
    | '/admin/leaderboards/beeps'
    | '/admin/leaderboards/rides'
    | '/admin/ratings/$ratingId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/users/domain'
    | '/password/reset/$id'
    | '/admin/beepers/'
    | '/admin/beeps/'
    | '/admin/cars/'
    | '/admin/feedback/'
    | '/admin/leaderboards/'
    | '/admin/notifications/'
    | '/admin/ratings/'
    | '/admin/reports/'
    | '/admin/users/'
    | '/admin/users/$userId/$'
    | '/admin/users/$userId/beeps'
    | '/admin/users/$userId/cars'
    | '/admin/users/$userId/edit'
    | '/admin/users/$userId/location'
    | '/admin/users/$userId/payments'
    | '/admin/users/$userId/queue'
    | '/admin/users/$userId/ratings'
    | '/admin/users/$userId/reports'
    | '/admin/users/$userId/ride'
    | '/admin/users/$userId/edit/$'
    | '/admin/users/$userId/edit/location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/download'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account/delete'
    | '/admin/health'
    | '/admin/payments'
    | '/admin/redis'
    | '/password/change'
    | '/password/forgot'
    | '/profile/edit'
    | '/account/verify/$id'
    | '/admin/beeps/$beepId'
    | '/admin/beeps/active'
    | '/admin/leaderboards/beeps'
    | '/admin/leaderboards/rides'
    | '/admin/ratings/$ratingId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/users/domain'
    | '/password/reset/$id'
    | '/admin/beepers'
    | '/admin/beeps'
    | '/admin/cars'
    | '/admin/feedback'
    | '/admin/leaderboards'
    | '/admin/notifications'
    | '/admin/ratings'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/users/$userId/$'
    | '/admin/users/$userId/beeps'
    | '/admin/users/$userId/cars'
    | '/admin/users/$userId/edit'
    | '/admin/users/$userId/location'
    | '/admin/users/$userId/payments'
    | '/admin/users/$userId/queue'
    | '/admin/users/$userId/ratings'
    | '/admin/users/$userId/reports'
    | '/admin/users/$userId/ride'
    | '/admin/users/$userId/edit/$'
    | '/admin/users/$userId/edit/location'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/download'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account/delete'
    | '/admin/health'
    | '/admin/payments'
    | '/admin/redis'
    | '/password/change'
    | '/password/forgot'
    | '/profile/edit'
    | '/account/verify/$id'
    | '/admin/beeps/$beepId'
    | '/admin/beeps/active'
    | '/admin/leaderboards/beeps'
    | '/admin/leaderboards/rides'
    | '/admin/ratings/$ratingId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/users/domain'
    | '/password/reset/$id'
    | '/admin/beepers/'
    | '/admin/beeps/'
    | '/admin/cars/'
    | '/admin/feedback/'
    | '/admin/leaderboards/'
    | '/admin/notifications/'
    | '/admin/ratings/'
    | '/admin/reports/'
    | '/admin/users/'
    | '/admin/users/$userId/$'
    | '/admin/users/$userId/beeps'
    | '/admin/users/$userId/cars'
    | '/admin/users/$userId/edit'
    | '/admin/users/$userId/location'
    | '/admin/users/$userId/payments'
    | '/admin/users/$userId/queue'
    | '/admin/users/$userId/ratings'
    | '/admin/users/$userId/reports'
    | '/admin/users/$userId/ride'
    | '/admin/users/$userId/edit/$'
    | '/admin/users/$userId/edit/location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  PasswordChangeRoute: typeof PasswordChangeRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  ProfileEditRoute: typeof ProfileEditRoute
  AccountVerifyIdRoute: typeof AccountVerifyIdRoute
  PasswordResetIdRoute: typeof PasswordResetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redis': {
      id: '/admin/redis'
      path: '/redis'
      fullPath: '/admin/redis'
      preLoaderRoute: typeof AdminRedisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/password/change': {
      id: '/password/change'
      path: '/password/change'
      fullPath: '/password/change'
      preLoaderRoute: typeof PasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/$id': {
      id: '/account/verify/$id'
      path: '/account/verify/$id'
      fullPath: '/account/verify/$id'
      preLoaderRoute: typeof AccountVerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/beepers/': {
      id: '/admin/beepers/'
      path: '/beepers'
      fullPath: '/admin/beepers/'
      preLoaderRoute: typeof AdminBeepersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beeps/': {
      id: '/admin/beeps/'
      path: '/beeps'
      fullPath: '/admin/beeps/'
      preLoaderRoute: typeof AdminBeepsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beeps/$beepId': {
      id: '/admin/beeps/$beepId'
      path: '/beeps/$beepId'
      fullPath: '/admin/beeps/$beepId'
      preLoaderRoute: typeof AdminBeepsBeepIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/beeps/active': {
      id: '/admin/beeps/active'
      path: '/beeps/active'
      fullPath: '/admin/beeps/active'
      preLoaderRoute: typeof AdminBeepsActiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/cars'
      fullPath: '/admin/cars/'
      preLoaderRoute: typeof AdminCarsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback/': {
      id: '/admin/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback/'
      preLoaderRoute: typeof AdminFeedbackIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboards/': {
      id: '/admin/leaderboards/'
      path: '/leaderboards'
      fullPath: '/admin/leaderboards/'
      preLoaderRoute: typeof AdminLeaderboardsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboards/beeps': {
      id: '/admin/leaderboards/beeps'
      path: '/leaderboards/beeps'
      fullPath: '/admin/leaderboards/beeps'
      preLoaderRoute: typeof AdminLeaderboardsBeepsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboards/rides': {
      id: '/admin/leaderboards/rides'
      path: '/leaderboards/rides'
      fullPath: '/admin/leaderboards/rides'
      preLoaderRoute: typeof AdminLeaderboardsRidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ratings/': {
      id: '/admin/ratings/'
      path: '/ratings'
      fullPath: '/admin/ratings/'
      preLoaderRoute: typeof AdminRatingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ratings/$ratingId': {
      id: '/admin/ratings/$ratingId'
      path: '/ratings/$ratingId'
      fullPath: '/admin/ratings/$ratingId'
      preLoaderRoute: typeof AdminRatingsRatingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/$reportId': {
      id: '/admin/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminReportsReportIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/domain': {
      id: '/admin/users/domain'
      path: '/users/domain'
      fullPath: '/admin/users/domain'
      preLoaderRoute: typeof AdminUsersDomainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/password/reset/$id': {
      id: '/password/reset/$id'
      path: '/password/reset/$id'
      fullPath: '/password/reset/$id'
      preLoaderRoute: typeof PasswordResetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/$': {
      id: '/admin/users/$userId/$'
      path: '/$'
      fullPath: '/admin/users/$userId/$'
      preLoaderRoute: typeof AdminUsersUserIdSplatRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/beeps': {
      id: '/admin/users/$userId/beeps'
      path: '/beeps'
      fullPath: '/admin/users/$userId/beeps'
      preLoaderRoute: typeof AdminUsersUserIdBeepsRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/cars': {
      id: '/admin/users/$userId/cars'
      path: '/cars'
      fullPath: '/admin/users/$userId/cars'
      preLoaderRoute: typeof AdminUsersUserIdCarsRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/location': {
      id: '/admin/users/$userId/location'
      path: '/location'
      fullPath: '/admin/users/$userId/location'
      preLoaderRoute: typeof AdminUsersUserIdLocationRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/payments': {
      id: '/admin/users/$userId/payments'
      path: '/payments'
      fullPath: '/admin/users/$userId/payments'
      preLoaderRoute: typeof AdminUsersUserIdPaymentsRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/queue': {
      id: '/admin/users/$userId/queue'
      path: '/queue'
      fullPath: '/admin/users/$userId/queue'
      preLoaderRoute: typeof AdminUsersUserIdQueueRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/ratings': {
      id: '/admin/users/$userId/ratings'
      path: '/ratings'
      fullPath: '/admin/users/$userId/ratings'
      preLoaderRoute: typeof AdminUsersUserIdRatingsRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/reports': {
      id: '/admin/users/$userId/reports'
      path: '/reports'
      fullPath: '/admin/users/$userId/reports'
      preLoaderRoute: typeof AdminUsersUserIdReportsRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/ride': {
      id: '/admin/users/$userId/ride'
      path: '/ride'
      fullPath: '/admin/users/$userId/ride'
      preLoaderRoute: typeof AdminUsersUserIdRideRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/admin/users/$userId/edit/$': {
      id: '/admin/users/$userId/edit/$'
      path: '/$'
      fullPath: '/admin/users/$userId/edit/$'
      preLoaderRoute: typeof AdminUsersUserIdEditSplatRouteImport
      parentRoute: typeof AdminUsersUserIdEditRoute
    }
    '/admin/users/$userId/edit/location': {
      id: '/admin/users/$userId/edit/location'
      path: '/location'
      fullPath: '/admin/users/$userId/edit/location'
      preLoaderRoute: typeof AdminUsersUserIdEditLocationRouteImport
      parentRoute: typeof AdminUsersUserIdEditRoute
    }
  }
}

interface AdminUsersUserIdEditRouteChildren {
  AdminUsersUserIdEditSplatRoute: typeof AdminUsersUserIdEditSplatRoute
  AdminUsersUserIdEditLocationRoute: typeof AdminUsersUserIdEditLocationRoute
}

const AdminUsersUserIdEditRouteChildren: AdminUsersUserIdEditRouteChildren = {
  AdminUsersUserIdEditSplatRoute: AdminUsersUserIdEditSplatRoute,
  AdminUsersUserIdEditLocationRoute: AdminUsersUserIdEditLocationRoute,
}

const AdminUsersUserIdEditRouteWithChildren =
  AdminUsersUserIdEditRoute._addFileChildren(AdminUsersUserIdEditRouteChildren)

interface AdminUsersUserIdRouteChildren {
  AdminUsersUserIdSplatRoute: typeof AdminUsersUserIdSplatRoute
  AdminUsersUserIdBeepsRoute: typeof AdminUsersUserIdBeepsRoute
  AdminUsersUserIdCarsRoute: typeof AdminUsersUserIdCarsRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRouteWithChildren
  AdminUsersUserIdLocationRoute: typeof AdminUsersUserIdLocationRoute
  AdminUsersUserIdPaymentsRoute: typeof AdminUsersUserIdPaymentsRoute
  AdminUsersUserIdQueueRoute: typeof AdminUsersUserIdQueueRoute
  AdminUsersUserIdRatingsRoute: typeof AdminUsersUserIdRatingsRoute
  AdminUsersUserIdReportsRoute: typeof AdminUsersUserIdReportsRoute
  AdminUsersUserIdRideRoute: typeof AdminUsersUserIdRideRoute
}

const AdminUsersUserIdRouteChildren: AdminUsersUserIdRouteChildren = {
  AdminUsersUserIdSplatRoute: AdminUsersUserIdSplatRoute,
  AdminUsersUserIdBeepsRoute: AdminUsersUserIdBeepsRoute,
  AdminUsersUserIdCarsRoute: AdminUsersUserIdCarsRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRouteWithChildren,
  AdminUsersUserIdLocationRoute: AdminUsersUserIdLocationRoute,
  AdminUsersUserIdPaymentsRoute: AdminUsersUserIdPaymentsRoute,
  AdminUsersUserIdQueueRoute: AdminUsersUserIdQueueRoute,
  AdminUsersUserIdRatingsRoute: AdminUsersUserIdRatingsRoute,
  AdminUsersUserIdReportsRoute: AdminUsersUserIdReportsRoute,
  AdminUsersUserIdRideRoute: AdminUsersUserIdRideRoute,
}

const AdminUsersUserIdRouteWithChildren =
  AdminUsersUserIdRoute._addFileChildren(AdminUsersUserIdRouteChildren)

interface AdminRouteChildren {
  AdminHealthRoute: typeof AdminHealthRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRedisRoute: typeof AdminRedisRoute
  AdminBeepsBeepIdRoute: typeof AdminBeepsBeepIdRoute
  AdminBeepsActiveRoute: typeof AdminBeepsActiveRoute
  AdminLeaderboardsBeepsRoute: typeof AdminLeaderboardsBeepsRoute
  AdminLeaderboardsRidesRoute: typeof AdminLeaderboardsRidesRoute
  AdminRatingsRatingIdRoute: typeof AdminRatingsRatingIdRoute
  AdminReportsReportIdRoute: typeof AdminReportsReportIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRouteWithChildren
  AdminUsersDomainRoute: typeof AdminUsersDomainRoute
  AdminBeepersIndexRoute: typeof AdminBeepersIndexRoute
  AdminBeepsIndexRoute: typeof AdminBeepsIndexRoute
  AdminCarsIndexRoute: typeof AdminCarsIndexRoute
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
  AdminLeaderboardsIndexRoute: typeof AdminLeaderboardsIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminRatingsIndexRoute: typeof AdminRatingsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHealthRoute: AdminHealthRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRedisRoute: AdminRedisRoute,
  AdminBeepsBeepIdRoute: AdminBeepsBeepIdRoute,
  AdminBeepsActiveRoute: AdminBeepsActiveRoute,
  AdminLeaderboardsBeepsRoute: AdminLeaderboardsBeepsRoute,
  AdminLeaderboardsRidesRoute: AdminLeaderboardsRidesRoute,
  AdminRatingsRatingIdRoute: AdminRatingsRatingIdRoute,
  AdminReportsReportIdRoute: AdminReportsReportIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRouteWithChildren,
  AdminUsersDomainRoute: AdminUsersDomainRoute,
  AdminBeepersIndexRoute: AdminBeepersIndexRoute,
  AdminBeepsIndexRoute: AdminBeepsIndexRoute,
  AdminCarsIndexRoute: AdminCarsIndexRoute,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
  AdminLeaderboardsIndexRoute: AdminLeaderboardsIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminRatingsIndexRoute: AdminRatingsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  PasswordChangeRoute: PasswordChangeRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  ProfileEditRoute: ProfileEditRoute,
  AccountVerifyIdRoute: AccountVerifyIdRoute,
  PasswordResetIdRoute: PasswordResetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
