/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as PasswordChangeRouteImport } from './routes/password/change'
import { Route as AdminUsersByDomainRouteRouteImport } from './routes/admin/usersByDomainRoute'
import { Route as AccountDeleteRouteImport } from './routes/account/delete'
import { Route as PasswordResetIdRouteImport } from './routes/password/reset.$id'
import { Route as AccountVerifyIdRouteImport } from './routes/account/verify.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordChangeRoute = PasswordChangeRouteImport.update({
  id: '/password/change',
  path: '/password/change',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersByDomainRouteRoute = AdminUsersByDomainRouteRouteImport.update({
  id: '/admin/usersByDomainRoute',
  path: '/admin/usersByDomainRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetIdRoute = PasswordResetIdRouteImport.update({
  id: '/password/reset/$id',
  path: '/password/reset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyIdRoute = AccountVerifyIdRouteImport.update({
  id: '/account/verify/$id',
  path: '/account/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/usersByDomainRoute': typeof AdminUsersByDomainRouteRoute
  '/password/change': typeof PasswordChangeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/profile/edit': typeof ProfileEditRoute
  '/account/verify/$id': typeof AccountVerifyIdRoute
  '/password/reset/$id': typeof PasswordResetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/usersByDomainRoute': typeof AdminUsersByDomainRouteRoute
  '/password/change': typeof PasswordChangeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/profile/edit': typeof ProfileEditRoute
  '/account/verify/$id': typeof AccountVerifyIdRoute
  '/password/reset/$id': typeof PasswordResetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/admin/usersByDomainRoute': typeof AdminUsersByDomainRouteRoute
  '/password/change': typeof PasswordChangeRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/profile/edit': typeof ProfileEditRoute
  '/account/verify/$id': typeof AccountVerifyIdRoute
  '/password/reset/$id': typeof PasswordResetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account/delete'
    | '/admin/usersByDomainRoute'
    | '/password/change'
    | '/password/forgot'
    | '/profile/edit'
    | '/account/verify/$id'
    | '/password/reset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account/delete'
    | '/admin/usersByDomainRoute'
    | '/password/change'
    | '/password/forgot'
    | '/profile/edit'
    | '/account/verify/$id'
    | '/password/reset/$id'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/account/delete'
    | '/admin/usersByDomainRoute'
    | '/password/change'
    | '/password/forgot'
    | '/profile/edit'
    | '/account/verify/$id'
    | '/password/reset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  AdminUsersByDomainRouteRoute: typeof AdminUsersByDomainRouteRoute
  PasswordChangeRoute: typeof PasswordChangeRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  ProfileEditRoute: typeof ProfileEditRoute
  AccountVerifyIdRoute: typeof AccountVerifyIdRoute
  PasswordResetIdRoute: typeof PasswordResetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/change': {
      id: '/password/change'
      path: '/password/change'
      fullPath: '/password/change'
      preLoaderRoute: typeof PasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usersByDomainRoute': {
      id: '/admin/usersByDomainRoute'
      path: '/admin/usersByDomainRoute'
      fullPath: '/admin/usersByDomainRoute'
      preLoaderRoute: typeof AdminUsersByDomainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset/$id': {
      id: '/password/reset/$id'
      path: '/password/reset/$id'
      fullPath: '/password/reset/$id'
      preLoaderRoute: typeof PasswordResetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify/$id': {
      id: '/account/verify/$id'
      path: '/account/verify/$id'
      fullPath: '/account/verify/$id'
      preLoaderRoute: typeof AccountVerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  AdminUsersByDomainRouteRoute: AdminUsersByDomainRouteRoute,
  PasswordChangeRoute: PasswordChangeRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  ProfileEditRoute: ProfileEditRoute,
  AccountVerifyIdRoute: AccountVerifyIdRoute,
  PasswordResetIdRoute: PasswordResetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
