name: backup

on:
  schedule:
    - cron: "33 8 * * *" # Run at 8:33am UTC every day (Will be the middle of the night in the US)
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  backup-and-upload:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt install -y postgresql-client jq s3cmd

      - name: Dump database
        run: pg_dump postgresql://${{ env.DB_USER }}:$( printf %s '${{ env.DB_PASSWORD }}'| jq -sRr @uri)@${{ env.DB_HOST_PUBLIC }}:5432/beep?sslmode=require | gzip > $(date -u +'%Y-%m-%d-%H-%M-%S').sql.gz
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST_PUBLIC: ${{ secrets.DB_HOST_PUBLIC }}

      - name: Upload backup
        run: s3cmd put --access_key=${{ env.S3_BACKUPS_ACCESS_KEY }} --secret-key=${{ env.S3_BACKUPS_SECRET_KEY }} --host=https://us-lax-1.linodeobjects.com s3://beep-backups/
        env:
          S3_BACKUPS_ACCESS_KEY: ${{ secrets.S3_BACKUPS_ACCESS_KEY }}
          S3_BACKUPS_SECRET_KEY: ${{ secrets.BACKUPS_SECRET_KEY }}
