name: backup

on:
  schedule:
    - cron: "33 8 * * *" # Run at 8:33am UTC every day (Will be the middle of the night in the US)
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  backup-and-upload:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt install -y postgresql-client jq

      - name: Dump database
        run: pg_dump postgresql://${{ env.DB_USER }}:$(echo "${{ env.DB_PASSWORD }}" | jq -sRr @uri)@${{ env.DB_HOST_PUBLIC }}:5432/beep | gzip > $(date -u +'%Y-%m-%d-%H-%M-%S').sql.gz
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST_PUBLIC: ${{ secrets.DB_HOST_PUBLIC }}
