name: dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.ridebeep.app
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest
      - run: pnpm i --frozen-lockfile
      - name: Set up WireGuard Connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
          work-dir: deploy
        env:
          PULUMI_K8S_ENABLE_PATCH_FORCE: true
          PULUMI_K8S_DELETE_UNREACHABLE: true
          secrets: ${{ toJSON(secrets) }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
