name: e2e

on:
  push:
    branches:
      - main
      - production
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v7
        with:
          node-version: latest
      - run: docker compose up -d
      - run: bun install --frozen-lockfile
      - run: bun playwright install --with-deps --only-shell chromium
        working-directory: ./test
      - run: bun drizzle-kit push --force
        working-directory: ./api
      - run: bun --filter @beep/test test
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-report
          path: |
            test/playwright-report/
            test/test-results/
          retention-days: 10
